### PR TITLE
feat: Add Speaker Consistency Evaluation Feature

### PR DESCRIPTION
**Pull request by 6drf21e**
This PR introduces a new feature for evaluating speaker consistency within the project. It includes scripts for generating test audio and assessing the stability of speakers' voice timbre using the ERes2NetV2 Speaker Recognition Model.

## Changes

- Added `audio_generator.py`: Script to generate test audio files based on text data provided in `test_data.yaml`.
- Added `consistency_evaluator.py`: Script to evaluate the stability of speaker voice timbre by calculating the cosine similarity between embedding vectors of audio segments.
- Included `test_data.yaml`: YAML file containing text data for generating audio.
- Updated `README.md` to include installation instructions, usage guidelines, and details about command-line arguments for both scripts.
- Added `requirements.txt` to specify dependencies required for running the scripts.

### CODE REVIEW

**Comment by 6drf21e** [comment]
colab test
https://colab.research.google.com/drive/1BzyUvrh1XBtaA6UqPLXiKyhUSitNJsqm

**Comment by fumiama** [comment]
Thanks for your contribution! This helps us a lot. 🤝
However, this repo aims to provide the ChatTTS package so it is hard to add too many bundles 😂.
If you agree, we want to invite you to contribute to a new repo in our organization, 2noise.
Then, we can link to your awesome work to the README in this main repo.

**Comment by fumiama** [comment]
All right 😂. I will decide by my self.

**Comment by fumiama** [comment]
And, what license would you like? (I suggest AGPL v3)

**Comment by fumiama** [comment]
OK.

**Comment by fumiama** [comment]
I have invited you to https://github.com/2noise/ChatEval
Therefore, I would like to close this PR first.
Feel free to push your codes there! 🎉

**Pull request closed without merging**
