### PR TITLE
Add apple gpu mps backend

### PR DESCRIPTION
**Pull request by rasonyang**
Add support Apple M1/M2 chips with Metal Performance Shaders

### CODE REVIEW

**Review by rasonyang — COMMENTED** [review]
Add support Apple M1/M2 chips with Metal Performance Shaders

**Comment by libukai** [comment]
Has the token generation speed slowed down instead?

**Comment by yihong0618** [comment]
this is not correct, will slower than CPU, the vocos part will fall back to CPU

**Review by fumiama — APPROVED** [review]
Thanks!

**Comment by libukai** [comment]
> Thanks!

建议不要合并这个 PR，会导致语音生成速度大幅减慢

**Comment by fumiama** [comment]
> > Thanks!
> 
> 建议不要合并这个 PR，会导致语音生成速度大幅减慢

非MPS设备吗？

**Pull request merged**
