### PR TITLE
support stream mode

### PR DESCRIPTION
**Pull request by Ox0400**
usage

```python
stream = True
wavs_gen = chat.infer('text here', stream=stream)

if stream:
     wavs = [np.array([[]])]
     for gen in wavs_gen:
         print('new chunk gen', gen)
         wavs[0] = np.hstack([wavs[0], np.array(gen[0])])
 else:
     print('check result', wavs_gen)
     wavs = wavs_gen

torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)

```

### CODE REVIEW

**Review by fumiama — CHANGES_REQUESTED** [review]
Thanks!

- You can pull the latest code and resolve conflict.
- You can add this stream version to `examples/webui` and `examples/cmd`

**Review by fumiama — APPROVED** [review]

**Comment by Ox0400** [comment]
@fumiama  Thanks for you fixed my abnormal code. I'm trying add  the tests to `examples/cmd`

**Comment by fumiama** [comment]
You're welcome. You can change the webui and cmd directly to the stream mode in order to support long-sentence infer.

**Comment by Ox0400** [comment]
> You're welcome. You can change the webui and cmd directly to the stream mode in order to support long-sentence infer.

Okay, For cli mode, PR:  https://github.com/2noise/ChatTTS/pull/366

web mode is some complexity, just the first chunk need `WAV` header bytes. `PCM` mode will be better.

**Comment by jackbapa** [comment]
stream模式下有异常噪声。

**Comment by fumiama** [comment]
> stream模式下有异常噪声。

怀疑是gradio处理问题

**Comment by Ox0400** [comment]
> > stream模式下有异常噪声。
> 
> 怀疑是gradio处理问题

stream 模式下用 PCM, 或者去掉 WAV 包头.

**Pull request merged**
