### PR TITLE
[Draft] Add FineTuning

### PR DESCRIPTION
**Pull request by ain-soph**
Hi, I follow [fish_speech](https://github.com/fishaudio/fish-speech) to implement a fine-tuning script (with a dataset class). 
I leave some placeholders for `Encoder` part (input `mel_specs` and output `(audio_quantized_latents, audio_input_ids)`).  
The training hyper-parameters are just a very basic setting.  
There are some todo parts in the codes that requires further check.  
Hope this could help the maintainersto release the fine-tuning codes more quickly.

我按照[fish_speech](https://github.com/fishaudio/fish-speech)写了个大概的fine-tuning脚本（和一个数据集类）。我给encoder（输入`mel_specs`输出`(audio_quantized_latents, audio_input_ids)`）留了些placeholder。  
训练用的超参是我瞎写的。  
代码里还有些todo注释需要进一步检查。  
希望这能帮助维护者更快地release他们的fine-tuning代码

### CODE REVIEW

**Comment by lanyuer** [comment]
可以微调成功吗

**Comment by ain-soph** [comment]
> 可以微调成功吗

还缺encoder部分作者没有release。看看要是作者近期不公布的话就自己写一个

**Comment by ain-soph** [comment]
Close this issue because of no official encoder support. I'll keep the fork and draft a new encoder myself.

**Comment by elvuel** [comment]
> Close this issue because of no official encoder support. I'll keep the fork and draft a new encoder myself.

@ain-soph 目前进展如何？

**Comment by ain-soph** [comment]
> > Close this issue because of no official encoder support. I'll keep the fork and draft a new encoder myself.
> 
> @ain-soph 目前进展如何？

上班没时间弄了，encoder写了一个但是效果不好。你要是想尝试可以自己改改去train

**Comment by crj1998** [comment]
> Hi, I follow [fish_speech](https://github.com/fishaudio/fish-speech) to implement a fine-tuning script (with a dataset class). I leave some placeholders for `Encoder` part (input `mel_specs` and output `(audio_quantized_latents, audio_input_ids)`). The training hyper-parameters are just a very basic setting. There are some todo parts in the codes that requires further check. Hope this could help the maintainersto release the fine-tuning codes more quickly.
> 
> 我按照[fish_speech](https://github.com/fishaudio/fish-speech)写了个大概的fine-tuning脚本（和一个数据集类）。我给encoder（输入`mel_specs`输出`(audio_quantized_latents, audio_input_ids)`）留了些placeholder。 训练用的超参是我瞎写的。 代码里还有些todo注释需要进一步检查。 希望这能帮助维护者更快地release他们的fine-tuning代码

能分享一下 数据集 处理脚本吗？
我现在有从视频上扒下来的原始音频，能分享一下去除背景音，分段，语音识别 得到如下数据格式的过程吗？语音识别 你使用是哪个模型啊，我用的模型没法标出标点符号。
```
888/888_1.wav|888|zh|哈喽大家好我是老八，欢迎收看地上足球，昨天晚上九点，梅哥在微博。
888/888_10.wav|888|zh|我告诉你，都有问题，如果你们还在质疑这个视频真实性的人。
```

**Comment by ain-soph** [comment]
@crj1998 这部分我没写，用的是乔希做的现成的数据集。下载代码和读取代码在fork都有，你如果能访问google的话可以直接自动下载。

**Comment by gafield-liu** [comment]
> > > Close this issue because of no official encoder support. I'll keep the fork and draft a new encoder myself.
> > 
> > 
> > @ain-soph 目前进展如何？
> 
> 上班没时间弄了，encoder写了一个但是效果不好。你要是想尝试可以自己改改去train

基于大佬的脚本修改了下已经可以训练，训练出来的语音中有比较明显的电音，还在想办法改进。

**Comment by ain-soph** [comment]
@gafield-liu 可以的话share一下代码，我周末瞧瞧怎么整。我自己对模型架构设计不熟，写的encoder训练不出来

**Pull request closed without merging**
